"""Generate the API reference Markdown under docs/api/ from data/api.json.

Everything under docs/api/ is generated -- never edit it by hand. Curated
content lives in overlays/api/ and is merged in here:

    overlays/api/<owner>/index.md      extra prose for a namespace / object page
    overlays/api/<owner>/<member>.md   examples / notes for one function

<owner> is the namespace name (`lcd`, `system`, ...) or the object class name
(`Source`, `Timer`, ...). Overlay files are plain Markdown and are inserted
verbatim under the "Examples" heading of the generated page.

Usage:
    python scripts/gen_api_pages.py [--api data/api.json] [--out docs/api]
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GENERATED = "<!-- GENERATED by scripts/gen_api_pages.py from data/api.json. Do not edit: add examples in overlays/api/ instead. -->\n"

# Variable names used in method signatures, e.g. `source:value()`.
INSTANCE_NAMES = {
    "FormFieldLib": "field", "ChoiceLib": "field", "NumberEditLib": "field",
    "SliderLib": "field", "TimeEditLib": "field", "FrSkyStaticTextLib": "field",
    "LuaSPortFrame": "frame", "LuaSPortSensor": "sensor", "LuaSPortSerial": "serial",
    "CrsfSensor": "sensor", "MultimoduleSensor": "sensor", "LogicSwitch": "ls",
    "ExpansionPanel": "panel", "GlassesLayout": "layout",
}

# Friendlier group titles for the constants page, by name prefix.
CONSTANT_GROUPS = [
    ("FONT_", "Fonts", "Used with `lcd.font()`."),
    ("THEME_", "Theme colors", "Used with `lcd.themeColor()` and `lcd.color()` so scripts follow the user's theme."),
    ("COLOR_", "Colors", "Fixed colors. Prefer `lcd.RGB()` or theme colors."),
    ("CATEGORY_", "Source categories", "Used with `system.getSource({category=...})` and `Source:category()`."),
    ("OPTION_", "Source options", "Used with `system.getSource({options=...})` and `Source:value({options=...})`."),
    ("SYSTEM_EVENT_", "System events", "Members of `CATEGORY_SYSTEM_EVENT`."),
    ("SYSTEM_", "System sources", "Members of `CATEGORY_SYSTEM`."),
    ("PEN_", "Pen styles", "Used with `lcd.pen()`."),
    ("TEXT_", "Text alignment", "Flags for `lcd.drawText()` / `lcd.drawNumber()`."),
    ("CURVE_TYPE_", "Curve types", "Used with `model.createCurve()` / `Curve`."),
    ("LOGIC_SWITCH_FUNCTION_", "Logic switch functions", "Used with `LogicSwitch:function()`."),
    ("EVT_", "Events", "Event categories passed to `event(widget, category, value, x, y)` handlers."),
    ("UNIT_", "Units", "Used with `Source:unit()` and `lcd.drawNumber()`."),
    ("SENSOR_TYPE_", "Sensor types", "Used with `model.createSensor()`."),
]
LEGACY = {"BLACK", "WHITE", "RED", "GREEN", "BLUE", "YELLOW", "ORANGE", "SOLID", "DOTTED",
          "RIGHT", "LEFT", "CENTERED"}


def vkey(v: str) -> tuple:
    return tuple(int(x) for x in re.findall(r"\d+", v or "0")[:3]) or (0,)


def slug(name: str) -> str:
    return name.lower().replace("_", "-")


class Gen:
    def __init__(self, api: dict, out: Path, overlays: Path, usage_roots: list[Path], real: dict | None = None):
        self.api = api
        self.real = real or {"repos": {}, "calls": {}}
        self.out = out
        self.overlays = overlays
        self.pages = api["pages"]
        self.namespaces = [p for p in self.pages if p["kind"] == "namespace" and p["name"] != "base"]
        self.classes = [p for p in self.pages if p["kind"] == "class"]
        self.documented_classes = [c for c in self.classes if c["members"]]
        self.class_names = {c["name"] for c in self.documented_classes}
        self.base = next((p for p in self.pages if p["name"] == "base"), {"members": []})
        self.constants = {m["name"] for m in self.base["members"]}
        versions = [m["since"] for p in self.pages for m in p["members"] if m.get("since")]
        self.latest = max(versions, key=vkey) if versions else ""
        self.usage = self.scan_usage(usage_roots)

    # ---------------------------------------------------------------- paths
    def owner_dir(self, page: dict) -> str:
        return f"objects/{page['name']}" if page["kind"] == "class" else page["name"]

    def member_rel(self, page: dict, member: dict) -> str:
        return f"{self.owner_dir(page)}/{member['name']}.md"

    def call_name(self, page: dict, member: dict) -> str:
        if page["kind"] == "class":
            inst = INSTANCE_NAMES.get(page["name"], page["name"][0].lower() + page["name"][1:])
            return f"{inst}:{member['name']}"
        return f"{page['name']}.{member['name']}"

    def title_name(self, page: dict, member: dict) -> str:
        sep = ":" if page["kind"] == "class" else "."
        return f"{page['name']}{sep}{member['name']}"

    # ---------------------------------------------------------------- usage
    def scan_usage(self, roots: list[Path]) -> dict[str, list[tuple[str, str]]]:
        """Map 'lcd.drawText' -> [(label, docs-relative md path)] from example pages."""
        found: dict[str, list[tuple[str, str]]] = defaultdict(list)
        calls = {}
        for p in self.namespaces:
            for m in p["members"]:
                if m["kind"] == "function":
                    calls[f"{p['name']}.{m['name']}"] = re.compile(rf"\b{re.escape(p['name'])}\.{re.escape(m['name'])}\s*\(")
        for root in roots:
            if not root.exists():
                continue
            for md in sorted(root.rglob("*.md")):
                text = md.read_text(encoding="utf-8")
                # cookbook pages embed their scripts with --8<-- "path"; scan the included code too
                text = re.sub(r'^--8<-- "([^"]+)"$',
                              lambda m: (ROOT / m.group(1)).read_text(encoding="utf-8")
                              if (ROOT / m.group(1)).exists() else "", text, flags=re.M)
                tm = re.search(r"^#\s+(.+)$", text, re.M)
                label = tm.group(1).strip() if tm else md.stem
                rel = md.relative_to(ROOT / "docs").as_posix()
                for key, rx in calls.items():
                    if rx.search(text):
                        found[key].append((label, rel))
        return found

    # ---------------------------------------------------------------- text helpers
    def link_types(self, text: str, depth: int) -> str:
        """Link object class names (Source, Timer, ...) appearing in type/return text."""
        if not text:
            return text
        up = "../" * depth

        def repl(m):
            name = m.group(0)
            return f"[{name}]({up}objects/{name}/index.md)"
        names = sorted(self.class_names, key=len, reverse=True)
        rx = re.compile(r"(?<![\w`/\[])(" + "|".join(map(re.escape, names)) + r")(?![\w`\]])")
        return rx.sub(repl, text)

    def signature(self, page: dict, member: dict) -> str:
        args = []
        opened = 0
        for p in member.get("params", []):
            name = re.sub(r"[^\w.]", "", p["name"]) or "arg"
            if p["optional"]:
                args.append(("[, " if args else "[") + name)
                opened += 1
            else:
                args.append((", " if args else "") + name)
        sig = "".join(args) + "]" * opened
        call = f"{self.call_name(page, member)}({sig})"
        ret = member.get("returns", "")
        rm = re.match(r"^\s*([A-Za-z_]\w*(?:\s*,\s*[A-Za-z_]\w*)*)\s*\(", ret)
        if rm and rm.group(1).lower() not in ("none", "the", "a", "an", "true", "false", "nil"):
            return f"local {rm.group(1)} = {call}"
        return call

    def badges(self, member: dict) -> str:
        out = []
        if member.get("since"):
            cls = "new" if member["since"] == self.latest else "since"
            out.append(f'<span class="api-badge api-badge--{cls}">since {member["since"]}</span>')
        if re.search(r"deprecated", member.get("brief", "") + member.get("description", ""), re.I):
            out.append('<span class="api-badge api-badge--deprecated">deprecated</span>')
        return " ".join(out)

    def overlay(self, owner: str, name: str) -> tuple[str, str | None]:
        path = self.overlays / owner / f"{name}.md"
        rel = path.relative_to(ROOT).as_posix()
        return rel, path.read_text(encoding="utf-8").strip() if path.exists() else None

    # ---------------------------------------------------------------- writers
    def write(self, rel: str, text: str) -> None:
        path = self.out / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")

    def front(self, overlay_rel: str, exists: bool, extra: dict | None = None) -> str:
        lines = ["---", f"overlay: {overlay_rel}", f"overlay_exists: {'true' if exists else 'false'}"]
        for k, v in (extra or {}).items():
            lines.append(f"{k}: {v}")
        lines.append("---")
        return "\n".join(lines) + "\n" + GENERATED + "\n"

    def gen_member(self, page: dict, member: dict) -> None:
        depth = self.owner_dir(page).count("/") + 1
        owner = page["name"]
        overlay_rel, overlay = self.overlay(owner, member["name"])
        title = self.title_name(page, member)
        o = [self.front(overlay_rel, overlay is not None, {"title": title})]
        o.append(f"# {title}\n")
        b = self.badges(member)
        if b:
            o.append(f'<div class="api-badges">{b}</div>\n')
        if member.get("brief"):
            o.append(member["brief"] + "\n")
        o.append(f"```lua\n{self.signature(page, member)}\n```\n")
        if member.get("description"):
            o.append(member["description"] + "\n")

        o.append("## Parameters\n")
        params = member.get("params", [])
        if params:
            o.append("| Name | Type | Required | Description |")
            o.append("| --- | --- | --- | --- |")
            for p in params:
                desc = p["description"]
                nested = ""
                if "\n" in desc:  # table-of-fields style params -> render list below
                    first, _, rest = desc.partition("\n")
                    desc, nested = first.strip(), rest.strip()
                ptype, optional = p["type"], p["optional"]
                if not ptype:  # upstream sometimes puts the type in the description instead
                    tm = re.match(r"^(table)\b\s*(.*)$", desc)
                    if tm:
                        ptype, desc = "table", tm.group(2) or desc
                        if re.fullmatch(r"(with )?elements:?", desc.strip()):
                            desc = "see the fields below"
                    else:
                        tm = re.search(r"\s*\((\w+)(,\s*optional)?\)\s*$", desc)
                        if tm and tm.group(1).lower() in ("string", "number", "integer", "boolean", "table", "function"):
                            ptype, optional = tm.group(1), optional or bool(tm.group(2))
                            desc = desc[:tm.start()].strip()
                req = "optional" if optional else "yes"
                if p.get("default"):
                    req = f"optional (default `{p['default']}`)"
                typ = self.link_types(ptype, depth) if ptype else ""
                o.append(f"| `{p['name']}` | {typ} | {req} | {desc.replace('|', '&#124;')} |")
                if nested:
                    o.append("")
                    o.append(f"Fields of `{p['name']}`:\n\n{nested}\n")
            o.append("")
        else:
            o.append("None.\n")

        o.append("## Returns\n")
        o.append((self.link_types(member["returns"], depth) if member.get("returns") else "Nothing.") + "\n")

        for n in member.get("notes", []):
            o.append(f'!!! note "{n["kind"].title()}"\n    ' + n["text"].replace("\n", "\n    ") + "\n")

        has_examples = member.get("examples") or overlay
        if has_examples:
            o.append("## Examples\n")
            if overlay:
                o.append(overlay + "\n")
            for i, ex in enumerate(member.get("examples", [])):
                label = "From the official Ethos documentation" if i == 0 else "More from the official documentation"
                o.append(f'```lua title="{label}"\n{ex}\n```\n')

        used = self.usage.get(f"{owner}.{member['name']}") if page["kind"] == "namespace" else None
        if used:
            o.append("## Used in\n")
            up = "../" * (depth + 1)
            for label, rel in used[:12]:
                o.append(f"- [{label}]({up}{rel})")
            o.append("")

        real = self.real["calls"].get(f"{owner}.{member['name']}") if page["kind"] == "namespace" else None
        if real and real["snippets"]:
            o.append("## Real-world usage\n")
            n_proj = len(real["projects"])
            o.append(f'<div class="api-usage">Called {real["count"]} times across {n_proj} open-source '
                     f'Ethos Lua project{"s" if n_proj != 1 else ""}. A few short excerpts:</div>\n')
            for n, sn in enumerate(real["snippets"], 1):
                meta = self.real["repos"].get(sn["repo"], {})
                label = f"Example {n}"  # neutral on purpose: projects aren't named as sources
                sha = meta.get("sha", "HEAD")
                last = sn["start"] + sn["snippet"].count("\n")
                url = f"https://github.com/{sn['repo']}/blob/{sha}/{sn['path']}#L{sn['start']}-L{last}"
                code = sn["snippet"].replace("\n", "\n    ")
                o.append(f'=== "{label}"\n\n    ```lua\n    {code}\n    ```\n\n'
                         f'    <small>[{sn["path"]}:{sn["start"]}]({url})</small>\n')

        # No custom prev/next pager: Material's footer already links neighbours,
        # and Markdown links inside a raw <div> are not rendered.
        self.write(self.member_rel(page, member), "\n".join(o))

    def obtained_from(self, cls: str) -> list[tuple[str, str]]:
        hits = []
        rx = re.compile(rf"\b{re.escape(cls)}\b")
        for p in self.namespaces + self.documented_classes:
            for m in p["members"]:
                if m["kind"] == "function" and rx.search(m.get("returns", "")) and p["name"] != cls:
                    hits.append((self.title_name(p, m), self.member_rel(p, m)))
        return hits

    def gen_owner(self, page: dict) -> None:
        owner = page["name"]
        odir = self.owner_dir(page)
        depth = odir.count("/") + 1
        overlay_rel, overlay = self.overlay(owner, "index")
        is_class = page["kind"] == "class"
        title = f"{owner} object" if is_class else f"{owner} namespace"
        o = [self.front(overlay_rel, overlay is not None, {"title": title})]
        o.append(f"# {owner}\n")
        if page.get("since"):
            o.append(f'<div class="api-badges"><span class="api-badge api-badge--since">since {page["since"]}</span></div>\n')
        if is_class:
            o.append(f"`{owner}` is an object type. You don't create it directly: you get one from another call, "
                     f"then call its methods with a colon, e.g. `{self.call_name(page, page['members'][0])}()`.\n")
        if page.get("description"):
            o.append(page["description"] + "\n")
        if overlay:
            o.append(overlay + "\n")
        for ex in page.get("examples", []):
            o.append(f"```lua\n{ex}\n```\n")

        if is_class:
            src = self.obtained_from(owner)
            if src:
                o.append("## Obtained from\n")
                up = "../" * depth
                for t, rel in src:
                    o.append(f"- [`{t}()`]({up}{rel})")
                o.append("")

        o.append("## Functions\n" if not is_class else "## Methods\n")
        o.append("| Function | Description | Since |")
        o.append("| --- | --- | --- |")
        for m in page["members"]:
            if m["kind"] != "function":
                continue
            dep = " *(deprecated)*" if re.search("deprecated", m.get("brief", ""), re.I) else ""
            brief = m.get("brief", "").replace("|", "&#124;")
            o.append(f"| [`{m['name']}()`]({m['name']}.md) | {brief}{dep} | {m.get('since', '')} |")
        o.append("")

        for base in page.get("bases", []):
            bp = next((c for c in self.documented_classes if c["name"] == base), None)
            if not bp:
                continue
            o.append(f"## Inherited from {base}\n")
            o.append("| Function | Description |")
            o.append("| --- | --- |")
            for m in bp["members"]:
                o.append(f"| [`{m['name']}()`](../{base}/{m['name']}.md) | {m.get('brief', '')} |")
            o.append("")

        self.write(f"{odir}/index.md", "\n".join(o))
        for m in page["members"]:
            if m["kind"] == "function":
                self.gen_member(page, m)

    def gen_constants(self) -> None:
        overlay_rel, overlay = self.overlay("constants", "index")
        o = [self.front(overlay_rel, overlay is not None, {"title": "Constants"})]
        o.append("# Constants\n")
        o.append("Global constants available to every Ethos Lua script. Use them by name, e.g. "
                 "`lcd.font(FONT_L)` or `system.getSource({category=CATEGORY_TELEMETRY_SENSOR, ...})`.\n")
        if overlay:
            o.append(overlay + "\n")
        remaining = list(self.base["members"])
        groups: list[tuple[str, str, list]] = []
        for prefix, label, blurb in CONSTANT_GROUPS:
            items = [m for m in remaining if m["name"].startswith(prefix) and m["name"] not in LEGACY]
            remaining = [m for m in remaining if m not in items]
            if items:
                groups.append((label, blurb, items))
        legacy = [m for m in remaining if m["name"] in LEGACY or "deprecated" in m.get("brief", "").lower()]
        other = [m for m in remaining if m not in legacy]
        if other:
            groups.append(("Other", "", other))
        if legacy:
            groups.append(("Legacy / deprecated", "Kept for older scripts. Prefer the `COLOR_*`, `PEN_*` and `TEXT_*` forms.", legacy))
        for label, blurb, items in groups:
            o.append(f"## {label}\n")
            if blurb:
                o.append(blurb + "\n")
            o.append("| Constant | Meaning |")
            o.append("| --- | --- |")
            for m in items:
                o.append(f'| <span id="{slug(m["name"])}"></span>`{m["name"]}` | {m.get("brief", "").replace("|", "&#124;")} |')
            o.append("")
        self.write("constants.md", "\n".join(o))

    def gen_index(self) -> None:
        overlay_rel, overlay = self.overlay("_api", "index")
        o = [self.front(overlay_rel, overlay is not None, {"title": "API reference"})]
        o.append("# API reference\n")
        src = self.api.get("source", {})
        if src:
            o.append(f'<div class="api-source">Generated from <code>lua-doc.zip</code> '
                     f'({src.get("release", "")}, fetched {src.get("fetched", "")}, sha256 <code>{src.get("sha256", "")[:12]}</code>).</div>\n')
        if overlay:
            o.append(overlay + "\n")
        o.append("## Namespaces\n")
        o.append("Global tables of functions, called with a dot: `lcd.drawText(...)`.\n")
        o.append("| Namespace | Functions | Since |")
        o.append("| --- | --- | --- |")
        for p in sorted(self.namespaces, key=lambda p: p["name"]):
            n = sum(1 for m in p["members"] if m["kind"] == "function")
            o.append(f"| [`{p['name']}`]({p['name']}/index.md) | {n} | {p.get('since', '')} |")
        o.append("")
        o.append("## Objects\n")
        o.append("Values returned by API calls, with methods called using a colon: `source:value()`.\n")
        o.append("| Object | Methods | Typical source |")
        o.append("| --- | --- | --- |")
        for c in sorted(self.documented_classes, key=lambda p: p["name"].lower()):
            n = sum(1 for m in c["members"] if m["kind"] == "function")
            src_from = self.obtained_from(c["name"])
            first = f"`{src_from[0][0]}()`" if src_from else ""
            o.append(f"| [`{c['name']}`](objects/{c['name']}/index.md) | {n} | {first} |")
        o.append("")
        opaque = sorted(c["name"] for c in self.classes if not c["members"])
        if opaque:
            o.append("Handle types with no methods of their own (passed between calls): "
                     + ", ".join(f"`{n}`" for n in opaque) + ".\n")
        o.append("## Constants\n")
        o.append(f"[{len(self.base['members'])} global constants](constants.md): fonts, theme colors, "
                 "source categories, units, events and more.\n")
        popular = sorted(self.real["calls"].items(), key=lambda kv: -kv[1]["count"])[:15]
        if popular:
            o.append("## Most used\n")
            o.append("The calls that real scripts use most, counted across the open-source projects listed in "
                     "[Real-world usage](../contributing/real-world-usage.md). Learn these first.\n")
            o.append("| Function | Calls | Projects |")
            o.append("| --- | --- | --- |")
            for fn, info in popular:
                ns, _, name = fn.partition(".")
                o.append(f"| [`{fn}()`]({ns}/{name}.md) | {info['count']} | {len(info['projects'])} |")
            o.append("")
        o.append("## What's new\n")
        newest = [(p, m) for p in self.namespaces + self.documented_classes for m in p["members"]
                  if m.get("since") == self.latest and m["kind"] == "function"]
        if newest:
            o.append(f"Added in **{self.latest}**:\n")
            for p, m in newest:
                o.append(f"- [`{self.title_name(p, m)}()`]({self.member_rel(p, m)}): {m.get('brief', '')}")
            o.append("")
        self.write("index.md", "\n".join(o))

    def gen_summary(self) -> None:
        o = ["<!-- GENERATED by scripts/gen_api_pages.py -->",
             "- [Overview](index.md)", "- [Constants](constants.md)", "- Namespaces"]
        for p in sorted(self.namespaces, key=lambda p: p["name"]):
            o.append(f"    - [{p['name']}]({p['name']}/index.md)")
            for m in p["members"]:
                if m["kind"] == "function":
                    o.append(f"        - [{m['name']}]({p['name']}/{m['name']}.md)")
        o.append("- Objects")
        for c in sorted(self.documented_classes, key=lambda p: p["name"].lower()):
            o.append(f"    - [{c['name']}](objects/{c['name']}/index.md)")
            for m in c["members"]:
                if m["kind"] == "function":
                    o.append(f"        - [{m['name']}](objects/{c['name']}/{m['name']}.md)")
        self.write("SUMMARY.md", "\n".join(o) + "\n")

    def gen_search_index(self) -> None:
        """Flat JSON index used by tools/agents (and handy for editors)."""
        rows = []
        for p in self.namespaces + self.documented_classes:
            for m in p["members"]:
                if m["kind"] == "function":
                    rows.append({"name": self.title_name(p, m), "signature": self.signature(p, m),
                                 "brief": m.get("brief", ""), "since": m.get("since", ""),
                                 "url": self.member_rel(p, m).replace(".md", "/")})
        self.write("api-index.json", json.dumps(rows, indent=1, ensure_ascii=False) + "\n")

    def run(self) -> None:
        if self.out.exists():
            shutil.rmtree(self.out)
        for p in self.namespaces + self.documented_classes:
            lowered = [m["name"].lower() for m in p["members"]]
            dupes = {n for n in lowered if lowered.count(n) > 1}
            if dupes:
                raise SystemExit(f"{p['name']}: members differ only by case {dupes} (breaks on Windows)")
            self.gen_owner(p)
        self.gen_constants()
        self.gen_index()
        self.gen_summary()
        self.gen_search_index()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--api", type=Path, default=ROOT / "data/api.json")
    ap.add_argument("--out", type=Path, default=ROOT / "docs/api")
    ap.add_argument("--overlays", type=Path, default=ROOT / "overlays/api")
    args = ap.parse_args()
    api = json.loads(args.api.read_text(encoding="utf-8"))
    usage_roots = [ROOT / "docs/cookbook", ROOT / "docs/examples"]
    usage_json = ROOT / "data/usage.json"
    real = json.loads(usage_json.read_text(encoding="utf-8")) if usage_json.exists() else None
    gen = Gen(api, args.out, args.overlays, usage_roots, real)
    gen.run()
    n = sum(1 for _ in args.out.rglob("*.md"))
    print(f"wrote {n} pages to {args.out} (latest API version: {gen.latest})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
