"""Parse the Doxygen HTML in FrSky's lua-doc.zip into data/api.json.

The upstream zip is generated by Doxygen from the Ethos firmware sources
(src/lua/api_*.cpp). It only ships HTML, so this parser walks the
`memitem` blocks of every namespace*.html / class*.html page and pulls out:

  brief, since, params, returns, code fragments (examples), other notes

Usage:
    python scripts/parse_lua_doc.py <extracted lua-doc dir> [-o data/api.json]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from bs4 import BeautifulSoup, Comment, NavigableString, Tag

# Types that appear inside "(type, optional): description" param strings.
PARAM_RE = re.compile(r"^\s*\((?P<inner>[^)]*)\)\s*:?\s*(?P<desc>.*)$", re.S)


# --------------------------------------------------------------------------
# HTML -> Markdown (only the small subset Doxygen emits here)
# --------------------------------------------------------------------------

def md(node, depth: int = 0) -> str:
    """Convert a Doxygen HTML fragment to Markdown."""
    if isinstance(node, Comment):
        return ""
    if isinstance(node, NavigableString):
        return re.sub(r"\s+", " ", str(node))
    if not isinstance(node, Tag):
        return ""
    name = node.name
    if name in ("script", "style"):
        return ""
    if name == "div" and "fragment" in (node.get("class") or []):
        return "\n\n```lua\n" + fragment_code(node) + "\n```\n\n"
    if name == "div" and "ttc" in (node.get("class") or []):
        return ""  # Doxygen tooltip payloads
    inner = "".join(md(c, depth) for c in node.children)
    if name == "code":
        return f"`{inner.strip()}`"
    if name in ("b", "strong"):
        return f"**{inner.strip()}**"
    if name in ("em", "i"):
        return f"*{inner.strip()}*"
    if name == "a":
        return inner  # internal doxygen links are rewritten later by name
    if name == "br":
        return "\n"
    if name == "p":
        return "\n\n" + inner.strip() + "\n\n"
    if name in ("ul", "ol"):
        items = []
        for i, li in enumerate(node.find_all("li", recursive=False), 1):
            bullet = "-" if name == "ul" else f"{i}."
            body = "".join(md(c, depth + 1) for c in li.children).strip()
            body = re.sub(r"\n\s*\n", "\n", body)
            body = body.replace("\n", "\n" + "  " * (depth + 1))
            items.append("  " * depth + f"{bullet} {body}")
        return "\n\n" + "\n".join(items) + "\n\n"
    return inner


def fragment_code(frag: Tag) -> str:
    lines = []
    for line in frag.find_all("div", class_="line"):
        # drop tooltip children so their text does not leak into code
        for ttc in line.find_all("div", class_="ttc"):
            ttc.decompose()
        lines.append(line.get_text().replace("\xa0", " ").rstrip())
    return "\n".join(lines).strip("\n")


def clean(text: str) -> str:
    text = re.sub(r"[ \t]+\n", "\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


# --------------------------------------------------------------------------
# Member parsing
# --------------------------------------------------------------------------

def parse_param_desc(raw: str) -> dict:
    """'(integer, optional): color value' -> {type, optional, description}."""
    m = PARAM_RE.match(raw)
    if not m:
        return {"type": "", "optional": False, "description": raw.strip()}
    parts = [p.strip() for p in m.group("inner").split(",")]
    default = next((re.sub(r"^default\s*=?\s*", "", p, flags=re.I) for p in parts if p.lower().startswith("default")), None)
    optional = default is not None or any(p.lower() in ("optional", "optonal") for p in parts)
    typ = ", ".join(p for p in parts if p.lower() not in ("optional", "optonal") and not p.lower().startswith("default"))
    out = {"type": typ, "optional": optional, "description": m.group("desc").strip()}
    if default is not None:
        out["default"] = default
    return out


TYPES = ("string", "number", "integer", "boolean", "table", "function", "Source", "Bitmap", "Mask")


def normalize_param(p: dict) -> dict:
    """Repair upstream inconsistencies so every parameter has a name and a type."""
    name, desc = p["name"], p["description"]
    m = re.fullmatch(r"(\w+)\((\w+)\)", name)                      # "pen(integer)"
    if m:
        p["name"], p["type"] = m.group(1), p["type"] or m.group(2)
    if p["name"] == "None" and desc.startswith("or "):              # "None" | "or condition (Source, optional)"
        m = re.match(r"or (\w+)\s*\((\w+)(?:,\s*optional)?\)", desc)
        if m:
            p["name"], p["type"], p["optional"] = m.group(1), m.group(2), True
            p["description"] = "omit to read the current value"
    if p["name"] in ("table",) and not p["type"]:                  # type used as the name
        p["name"], p["type"] = "params", "table"
    if not p["type"]:
        if re.match(r"function\s*\(", desc):                        # "function(state)"
            p["type"] = "function"
        m = re.search(r"\((\w+)(?:,\s*(optional|default (?:is |= ?)?(\S+?)))?\)\s*$", desc)
        if m and m.group(1) in TYPES:                               # "index (number, default is 0)"
            p["type"] = m.group(1)
            if m.group(2):
                p["optional"] = True
                if m.group(3):
                    p["default"] = m.group(3)
            p["description"] = desc[:m.start()].strip()
    return p


def parse_memdoc(doc: Tag) -> dict:
    out: dict = {"brief": "", "description": "", "since": "", "params": [],
                 "returns": "", "examples": [], "notes": []}
    body_parts: list[str] = []

    for child in list(doc.children):
        if isinstance(child, Comment):
            continue
        if isinstance(child, NavigableString):
            if child.strip():
                body_parts.append(str(child))
            continue
        if not isinstance(child, Tag):
            continue
        classes = child.get("class") or []
        if child.name == "div" and "fragment" in classes:
            out["examples"].append(fragment_code(child))
            continue
        if child.name == "dl":
            if "params" in classes:
                for row in child.select("table.params > tr"):
                    cells = row.find_all("td", recursive=False)
                    if len(cells) < 2:
                        continue
                    pname = cells[0].get_text(" ", strip=True)
                    raw = clean(md(cells[1]))
                    if pname.lower() == "none" and not raw:
                        continue
                    p = parse_param_desc(raw)
                    p["name"] = pname
                    out["params"].append(normalize_param(p))
                continue
            dt = child.find("dt")
            dd = child.find("dd")
            if dd:  # Doxygen sometimes nests the following code example inside a section
                for frag in dd.find_all("div", class_="fragment"):
                    out["examples"].append(fragment_code(frag))
                    frag.decompose()
            label = dt.get_text(strip=True).lower() if dt else ""
            value = clean(md(dd)) if dd else ""
            if "since" in classes:
                out["since"] = value
            elif "return" in classes:
                out["returns"] = "" if value.lower() == "none" else value
            else:
                out["notes"].append({"kind": label or "note", "text": value})
            continue
        body_parts.append(md(child))

    body = clean("".join(body_parts))
    if body:
        first, _, rest = body.partition("\n\n")
        out["brief"] = first.strip()
        out["description"] = rest.strip()
    return out


def parse_page(path: Path) -> dict | None:
    html = path.read_text(encoding="utf-8")
    # html.parser collapses whitespace-only text nodes, which would destroy
    # code indentation inside <div class="line">; pin it with NBSPs first.
    html = re.sub(r'(<div class="line">)( +)', lambda m: m.group(1) + " " * len(m.group(2)), html)
    soup = BeautifulSoup(html, "html.parser")
    title_el = soup.select_one(".headertitle .title")
    if not title_el:
        return None
    first = next((t for t in title_el.strings if t.strip()), "")
    name = re.sub(r"<.*", "", first.strip()).split()[0]
    kind = "class" if path.name.startswith("class") else "namespace"

    page = {"name": name, "kind": kind, "file": path.name, "since": "",
            "description": "", "examples": [], "bases": [], "members": []}

    # Inheritance: "Public Member Functions inherited from <a>FormFieldLib< X ></a>"
    for hdr in soup.select("tr.inherit_header a.el"):
        base = re.sub(r"<.*", "", hdr.get_text(strip=True)).strip()
        if base and base != name and base not in page["bases"]:
            page["bases"].append(base)

    details = soup.find("a", id="details")
    if details:
        block = details.find_next_sibling("div", class_="textblock")
        if block:
            info = parse_memdoc(block)
            page["since"] = info["since"]
            page["description"] = clean("\n\n".join(x for x in (info["brief"], info["description"]) if x))
            page["examples"] = info["examples"]

    # Which section each member sits in (Function / Constant / Member Function ...)
    for h2 in soup.select("h2.memtitle"):
        item = h2.find_next_sibling("div", class_="memitem")
        if not item:
            continue
        section_el = h2.find_previous("h2", class_="groupheader")
        section = section_el.get_text(strip=True) if section_el else ""
        memname_el = item.select_one("td.memname")
        full = memname_el.get_text(" ", strip=True) if memname_el else h2.get_text(strip=True)
        member = full.split("::")[-1].strip()
        is_func = "(" in h2.get_text() or "Function" in section
        doc = item.select_one(".memdoc")
        info = parse_memdoc(doc) if doc else {}
        page["members"].append({
            "name": member,
            "kind": "function" if is_func else "constant",
            "anchor": h2.find_previous("a", id=True).get("id") if h2.find_previous("a", id=True) else "",
            **info,
        })

    # Doxygen sorts the detailed docs alphabetically; the summary table at the
    # top keeps source order, which groups related calls (getX next to setX).
    order = {}
    for i, row in enumerate(soup.select("table.memberdecls tr[id^=r_]")):
        if "inherit" in (row.get("class") or []):
            continue
        order.setdefault(row["id"][2:], i)
    page["members"].sort(key=lambda m: order.get(m["anchor"], 10_000))
    return page


def parse_dir(src: Path) -> dict:
    pages = []
    for path in sorted(src.glob("*.html")):
        if not (path.name.startswith("namespace") or path.name.startswith("class")):
            continue
        if path.name.endswith("-members.html") or path.name.startswith("namespacemembers"):
            continue
        if path.name in ("namespaces.html", "classes.html"):
            continue
        page = parse_page(path)
        if page:
            pages.append(page)

    # Landing text from index.html
    intro = ""
    index = src / "index.html"
    if index.exists():
        soup = BeautifulSoup(index.read_text(encoding="utf-8"), "html.parser")
        tb = soup.select_one(".contents .textblock")
        if tb:
            for a in tb.select("a.anchor"):
                a.decompose()
            intro = clean(md(tb))

    return {"intro": intro, "pages": pages}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("src", type=Path, help="extracted lua-doc directory")
    ap.add_argument("-o", "--out", type=Path, default=Path("data/api.json"))
    ap.add_argument("--meta", type=Path, default=None, help="optional JSON with source metadata to embed")
    args = ap.parse_args()

    api = parse_dir(args.src)
    if args.meta and args.meta.exists():
        api["source"] = json.loads(args.meta.read_text(encoding="utf-8"))
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(api, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    n_ns = sum(1 for p in api["pages"] if p["kind"] == "namespace")
    n_cls = sum(1 for p in api["pages"] if p["kind"] == "class")
    n_fn = sum(1 for p in api["pages"] for m in p["members"] if m["kind"] == "function")
    n_const = sum(1 for p in api["pages"] for m in p["members"] if m["kind"] == "constant")
    print(f"parsed {n_ns} namespaces, {n_cls} classes, {n_fn} functions, {n_const} constants -> {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
