"""Turn FrSky's official Lua examples into pages under docs/examples/official/.

Source: https://github.com/FrSkyRC/ETHOS-Feedback-Community/tree/HEAD/lua/examples

Each example folder becomes one Markdown page showing every .lua file, with
its images copied alongside. A README in the folder (if any) is used as the
introduction. Short descriptions for the index live in DESCRIPTIONS below;
add one when a new example appears upstream (the build still works without).

Usage:
    python scripts/sync_examples.py <path to .../lua/examples>
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs/examples/official"
UPSTREAM = "https://github.com/FrSkyRC/ETHOS-Feedback-Community/tree/HEAD/lua/examples"

DESCRIPTIONS = {
    "active-look": "Drive ActiveLook smart glasses (`glasses` namespace).",
    "bluetooth": "Scan and connect Bluetooth devices (`bluetooth` namespace).",
    "custom-sensor": "Create a telemetry sensor whose value is computed in Lua.",
    "layout": "Register a custom screen layout (`system.registerLayout`).",
    "lazy-loading": "Keep startup RAM small by loading tool/widget code on first use.",
    "memstatus": "Background task that prints Lua and bitmap RAM every few seconds.",
    "source": "Register a Lua source that other parts of the model can use.",
    "task": "Minimal background task (`system.registerTask`).",
    "theme": "Register a custom color theme.",
    "tool-form": "System tool built from form fields.",
    "tool-servo": "System tool that drives a servo channel.",
    "widget-flvss": "Widget showing FLVSS LiPo cell voltages.",
    "widget-form": "Widget with a configuration form and persistent settings.",
    "widget-gauge": "Gauge widget with configurable source and colors.",
    "widget-jet": "Jet turbine dashboard using bitmap dials.",
    "widget-lcddemo": "Tour of the `lcd` drawing API.",
    "widget-rssi": "Classic RSSI bar widget.",
    "widget-sinus": "The smallest useful widget: draws a sine wave.",
    "wizard": "Model setup wizard built with forms.",
    "xxxxl": "Large-text value widget.",
}


def kind_of(name: str, code: str) -> str:
    for fn, label in (("registerWidget", "Widget"), ("registerSystemTool", "System tool"),
                      ("registerTask", "Task"), ("registerSource", "Source"),
                      ("registerSensor", "Sensor"), ("registerLayout", "Layout"),
                      ("registerTheme", "Theme")):
        if fn in code:
            return label
    return "Script"


def build(src: Path) -> None:
    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)
    rows = []
    for ex in sorted(p for p in src.iterdir() if p.is_dir()):
        name = ex.name
        lua_files = sorted(ex.rglob("*.lua"), key=lambda p: (p.name != "main.lua", p.as_posix()))
        if not lua_files:
            continue
        code_all = "\n".join(f.read_text(encoding="utf-8", errors="replace") for f in lua_files)
        kind = kind_of(name, code_all)
        desc = DESCRIPTIONS.get(name, "")

        assets = OUT / name
        images = [p for p in ex.rglob("*") if p.suffix.lower() in (".png", ".jpg", ".bmp")]
        for img in images:
            dst = assets / img.relative_to(ex)
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(img, dst)

        o = ["<!-- GENERATED by scripts/sync_examples.py. Do not edit. -->", f"# {name}\n"]
        o.append(f'<div class="api-badges"><span class="api-badge api-badge--since">{kind}</span>'
                 f' <a class="api-badge" href="{UPSTREAM}/{name}">view on GitHub</a></div>\n')
        if desc:
            o.append(desc + "\n")
        readme = next((p for p in ex.iterdir() if p.name.lower().startswith("readme")), None)
        if readme:
            text = readme.read_text(encoding="utf-8", errors="replace").strip()
            text = re.sub(r"^#\s+.*\n", "", text)  # drop its own H1
            if readme.suffix.lower() == ".md":
                o.append(re.sub(r"^(#+)", r"#\1", text, flags=re.M) + "\n")
            else:
                o.append("```text\n" + text + "\n```\n")
        o.append(f"Install: copy the folder to `SCRIPTS:/{name}/` on the radio (or the simulator's `scripts/` folder) and restart.\n")
        for f in lua_files:
            rel = f.relative_to(ex).as_posix()
            code = f.read_text(encoding="utf-8", errors="replace").rstrip()
            o.append(f'```lua title="{rel}" linenums="1"\n{code}\n```\n')
        if images:
            o.append("## Assets\n")
            for img in images:
                rel = img.relative_to(ex).as_posix()
                o.append(f"![{rel}]({name}/{rel}){{ loading=lazy style=\"max-height:120px\" }}")
            o.append("")
        (OUT / f"{name}.md").write_text("\n".join(o), encoding="utf-8")
        rows.append((name, kind, desc))

    idx = ["<!-- GENERATED by scripts/sync_examples.py. Do not edit. -->", "# Official examples\n",
           f"These are FrSky's own example scripts from [ETHOS-Feedback-Community]({UPSTREAM}), "
           "copied here so you can read and search them alongside the API reference. "
           "API pages link back here under **Used in**.\n",
           "| Example | Type | What it shows |", "| --- | --- | --- |"]
    for name, kind, desc in rows:
        idx.append(f"| [{name}]({name}.md) | {kind} | {desc} |")
    (OUT / "index.md").write_text("\n".join(idx) + "\n", encoding="utf-8")
    print(f"synced {len(rows)} official examples -> {OUT}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("src", type=Path, help="path to ETHOS-Feedback-Community/lua/examples")
    args = ap.parse_args()
    if not args.src.is_dir():
        print(f"not a directory: {args.src}", file=sys.stderr)
        return 1
    build(args.src)
    return 0


if __name__ == "__main__":
    sys.exit(main())
